bl_info = { "name": "ASURT-CDT",
            "author": "Khaled Ghobashy",
            "version": (1, 0, 0),
            "blender": (2, 7, 9),
            "description": "Visualize Animations Generated by asurt",
            "category": "3D View"}


import bpy

from .panels import *
from .operators import *

def register():
    bpy.utils.register_module(__name__)
    
    bpy.types.Scene.subsys_id = bpy.props.StringProperty \
      (name = 'SUB_ID',
      description = 'Enter the SubSystem ID used in the Assembly.',
      default = '')
      
    bpy.types.Scene.blmbs_path = bpy.props.StringProperty \
      (name = '',
      default = '',
      description = 'Browse for the script file of the model.',
      subtype = 'FILE_PATH')
    
    bpy.types.Scene.scpt_path = bpy.props.StringProperty \
      (name = '',
      default = '',
      description = 'Define the script file of the system.',
      subtype = 'FILE_PATH')
    
    bpy.types.Scene.cfg_path = bpy.props.StringProperty \
      (name = '',
      default = '',
      description = 'Define the config. file of the system.',
      subtype = 'FILE_PATH')
      
    bpy.types.Scene.sim_path = bpy.props.StringProperty \
      (name = '',
      default = '',
      description = 'Define the simulation results file of the system.',
      subtype = 'FILE_PATH')
      
      
      
def unregister():
    global loaded_instances, loaded_models
    bpy.utils.unregister_module(__name__)
    del bpy.types.Scene.scpt_path
    del bpy.types.Scene.cfg_path
    del bpy.types.Scene.sim_path
    del bpy.types.Scene.blmbs_path
    del loaded_instances
    del loaded_models
    

if __name__ == '__main__':
    register()

print('Loaded ASURT-CDT')
